In [1]:
import pandas as pd
import sqlite3 as sql
import numpy as np

In [2]:
conn = sql.connect('../database/bayesatbat.db')
c = conn.cursor()

In [3]:
sql_query = pd.read_sql_query("""SELECT * from Altuve""",conn)

In [4]:
df =pd.DataFrame(sql_query, columns=['pitch_type','p_throws','launch_speed','launch_angle','release_speed'])

In [5]:
def LAtoLS(row,bottomDEG,TopDEG,bottomSpeed,TopSpeed):
    
    if row['launch_speed']>=bottomSpeed and row['launch_speed']<TopSpeed and row['launch_angle']>=bottomDEG and row['launch_angle']<TopDEG:
        val=1
    else:
        val=0
        
    return val

In [6]:
def LA(row,bottomSpeed,TopSpeed):
    if row['launch_speed']>=bottomSpeed and row['launch_speed']<TopSpeed:
        val=1
    else: val=0
    return val

In [7]:
for i in range(0,130,10):
    bottom =i
    top =i+10
    df[f'{bottom} to {top}MPH']=df.apply(LA,args=(bottom,top),axis=1)
    print(bottom,top)

0 10
10 20
20 30
30 40
40 50
50 60
60 70
70 80
80 90
90 100
100 110
110 120
120 130

In [8]:
df[df['launch_angle'].notna()]

,pitch_type,p_throws,launch_speed,launch_angle,0 to 10MPH,10 to 20MPH,20 to 30MPH,30 to 40MPH,40 to 50MPH,50 to 60MPH,60 to 70MPH,70 to 80MPH,80 to 90MPH,90 to 100MPH,100 to 110MPH,110 to 120MPH,120 to 130MPH
0,FC,R,92.5,-14.0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,FC,R,92.4,44.0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,FC,R,81.5,2.0,0,0,0,0,0,0,0,0,1,0,0,0,0
5,FF,R,83.3,0.0,0,0,0,0,0,0,0,0,1,0,0,0,0
6,FF,L,75.4,32.0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2477,CU,R,73.5,-32.0,0,0,0,0,0,0,0,1,0,0,0,0,0
2480,FA,R,85.1,67.0,0,0,0,0,0,0,0,0,1,0,0,0,0
2481,FA,R,64.8,70.0,0,0,0,0,0,0,1,0,0,0,0,0,0
2482,CS,R,88.8,17.0,0,0,0,0,0,0,0,0,1,0,0,0,0
2484,FA,R,101.1,24.0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [9]:
def launch_angle(row,bottom_angle,Top_angle):
    
    if row['launch_angle']>=bottom_angle and row['launch_angle']<Top_angle:
        val=1
    else: val=0
    return val

In [11]:
for i in range(-90,90,10):
    bottom =i
    top =i+10
    df[f'{bottom}to{top}deg']=df.apply(launch_angle,args=(bottom,top),axis=1)
    print(bottom,top)

-90 -80
-80 -70
-70 -60
-60 -50
-50 -40
-40 -30
-30 -20
-20 -10
-10 0
0 10
10 20
20 30
30 40
40 50
50 60
60 70
70 80
80 90

In [13]:
df[df['launch_speed'].notna()]

,pitch_type,p_throws,launch_speed,launch_angle,0 to 10MPH,10 to 20MPH,20 to 30MPH,30 to 40MPH,40 to 50MPH,50 to 60MPH,...,-10to0deg,0to10deg,10to20deg,20to30deg,30to40deg,40to50deg,50to60deg,60to70deg,70to80deg,80to90deg
0,FC,R,92.5,-14.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,FC,R,92.4,44.0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,FC,R,81.5,2.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,FF,R,83.3,0.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,FF,L,75.4,32.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2477,CU,R,73.5,-32.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2480,FA,R,85.1,67.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2481,FA,R,64.8,70.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2482,CS,R,88.8,17.0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2484,FA,R,101.1,24.0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [16]:
df[4:]

,pitch_type,p_throws,launch_speed,launch_angle,0 to 10MPH,10 to 20MPH,20 to 30MPH,30 to 40MPH,40 to 50MPH,50 to 60MPH,...,-10to0deg,0to10deg,10to20deg,20to30deg,30to40deg,40to50deg,50to60deg,60to70deg,70to80deg,80to90deg
4,FC,R,81.5,2.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,FF,R,83.3,0.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,FF,L,75.4,32.0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,FF,L,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,FF,L,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2483,FA,R,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2484,FA,R,101.1,24.0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2485,FA,R,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2486,FA,R,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2487,CU,R,NaN,NaN,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0